# Generated by Django 3.2.21 on 2024-01-21 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_alter_post_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('amount', models.CharField(max_length=12)),
                ('type', models.IntegerField(choices=[(0, 'once_off'), (1, 'recurring')], default=0)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('budget_month', models.CharField(blank=True, max_length=7, null=True)),
                ('frequency', models.IntegerField(choices=[(0, 'NA'), (1, 'daily'), (2, 'weekly'), (3, 'monthly')], default=0)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['payment_date', 'created_on'],
            },
        ),
    ]
