# Generated by Django 3.2.21 on 2024-01-21 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_expense'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='type',
            new_name='payment_type',
        ),
    ]
